name: mobile_swifty_companion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  oauth2: ^2.0.3
  url_launcher: ^6.3.1
  uni_links: ^0.5.1
  app_links: ^6.3.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
